version: "3.9"
services:
  nodejs:
    build: './docker/nodejs/'
    networks:
        - backend
    ports:
        - "9000:9000"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: nodejs
    entrypoint: /bin/sh
    command:
      - -c
      - |
        tail -f /dev/null
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - node_mysql_db:/var/lib/mysql
      - ${PROJECT_ROOT}/:/var/www/html/
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend
networks:
  backend:
volumes:
  node_mysql_db:
    external: true
